# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'norty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for norty
  pod 'SideMenu'
  pod 'Hero'
  pod 'Cheetah'
  pod 'Firebase/Analytics'
  pod 'Firebase/AdMob'
  pod 'FontAwesome.swift'
  pod 'ViewAnimator'
  target 'nortyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nortyUITests' do
    # Pods for testing
  end

end
